name: Modify APK and Release

on:
  push:
    branches:
      - main

jobs:
  modify_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O $HOME/apktool
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O $HOME/apktool.jar
          chmod +x $HOME/apktool
          sudo mv $HOME/apktool /usr/local/bin/
          sudo mv $HOME/apktool.jar /usr/local/bin/

      - name: Download base.apk
        run: wget https://archive.monarch.army/content/cdn/EAStrOqPidGd/base.apk

      - name: Decompiling APK
        run: apktool d base.apk -o decompiled_apk

      - name: Modify smali file
        run: python modify.py

      - name: Recompile APK
        run: apktool b decompiled_apk -o modded_10.9.2.apk

      # Additional steps for signing the APK if required

      - name: Upload to releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./modded_10.9.2.apk
          asset_name: modded_10.9.2.apk
          asset_content_type: application/vnd.android.package-archive
